LCD.h
LCD_H
void lcdWriteString(char *string, unsigned char line)
Feed character string, and line (1 or 2)
File: LCD.h Author: GrantDescription: Contains the public interface for the LCD module.Created on 17 September 2014, 9:01 PM Function: lcdWriteString(char *string, unsigned char line)Include: LCD.hDescription:Arguments: string - line -Returns: None
References LINE1, LINE2, LINESTART, LINEEND, lcdWrite, SETDDRAMADD, LCD_INS, LCD_DATA, delay.
void lcdWriteChar(unsigned char byte, unsigned char line, unsigned char column)
Feed character string, and line (1 or 2)
Feed character string, and line (1 or 2) Function: lcdWriteChar(unsigned char byte, unsigned char line, unsigned char column)Include: LCD.hDescription:Arguments: byte - line - column -Returns: None
References LINE1, LINE2, lcdWrite, SETDDRAMADD, LCD_INS, LCD_DATA, delay.
void lcdInit(void)
Feed character, line (1 or 2), and column(1-16)
Feed character, line (1 or 2), and column(1-16) File: User_Interface.c Author:Description: Contains all the interface to the LCD hardwareDuties: -Interfaces with and controls the LCD -Displays data on the LCDCreated on 15 September 2014, 1:21 PM Function: lcdInit(void)Include: LCD.hDescription: Initialises the LCD hardware so that data can be displayed on the LCD in local interface modeArguments: NoneReturns: None
References delay, LCD_DATA_LINE_DIR, LCD_OUTPUT, LCD_RS_DIR, LCD_PIN_OUTPUT, LCD_RW_DIR, LCD_E_DIR, LCD_E, LCD_CLKLOW, LCD_RS, LCD_INS, LCD_RW, LCD_WRITE, lcdWrite, SETDISPFXN, DL_8BIT, N_2LINE, F_5X7DOT, DISPOPT, D_DISPON, C_CURSOFF, B_BLINKON, SETENTRYMODE, ID_CURSL, SH_DISPNSHIFT, DISPCLR.
Referenced by initialiseMenu.
void delay(unsigned int t)
Include:
Function: delay(void)Description:Arguments: t -Returns: None
Referenced by lcdInit, lcdBusy, lcdWrite, lcdWriteString, lcdWriteChar.
char lcdBusy(void)
Include:
Function: lcdBusy(void)Description:Arguments: NoneReturns: None
References LCD_RS_DIR, LCD_PIN_OUTPUT, LCD_RW_DIR, LCD_E_DIR, LCD_DATA_LINE_DIR, LCD_INPUT, LCD_E, LCD_CLKLOW, LCD_RW, LCD_READ, LCD_RS, LCD_INS, LCD_CLKHGH, delay, LCD_D7, BF_BUSY, LCD_OUTPUT.
Referenced by lcdWrite.
void lcdWrite(unsigned char byte, unsigned char mode)
Include: LCD.h.
Function: lcdWrite(unsigned char byte, unsigned char mode)Description:Arguments: byte - mode -Returns: None
References lcdBusy, LCD_DATA_LINE_DIR, LCD_OUTPUT, LCD_RW, LCD_WRITE, LCD_RS, LCD_DATA_LINE, delay, LCD_E, LCD_CLKHGH, LCD_CLKLOW.
Referenced by lcdInit, lcdWriteString, lcdWriteChar.