Menusystem.h
const rom char newLine[][]
Referenced by dispTrack.
const rom char CHOOSE[][]
Referenced by dispTopOptions, dispAzOptions, dispElOptions, dispRngOptions.
const rom char menuPrefix3[][]
Referenced by dispRngOptions.
const rom char menuPrefix4[][]
Referenced by dispAzOptions, dispElOptions.
const rom char menuPrefix5[][]
Referenced by dispAzOptions, dispElOptions.
const rom char menuPrefix8[][]
Referenced by dispRngOptions.
const rom char goUp[][]
Referenced by dispAzOptions, dispElOptions, dispRngOptions.
const rom char goUp2[][]
const rom char errNumOutOfRange[][]
Referenced by errOutOfRange.
const rom char and[][]
Referenced by errOutOfRange.
const rom char welcome[][]
Referenced by initialization.
const rom char welcomeLcd[][]
const far rom char topOption1[][]
Referenced by dispTopOptions.
const far rom char topOption2[][]
Referenced by dispTopOptions.
const far rom char topOption3[][]
Referenced by dispTopOptions.
const far rom char topOption4[][]
Referenced by dispTopOptions.
const far rom char topOption5[][]
Referenced by dispTopOptions.
const far rom char topOptionCalTemp[][]
Referenced by dispTopOptions.
const far rom char topOptionLocal[][]
Referenced by dispTopOptions.
const far rom char topOptionFactory[][]
const far rom char topOptionRemote[][]
Referenced by dispTopOptions.
const far rom char topOptionRemoteLCD[][]
Referenced by dispLCDTopMenu.
const rom char azMenu[][]
const rom char azMenuLcd[][]
const far rom char azOption1[][]
Referenced by dispAzOptions.
const far rom char azOption2[][]
Referenced by dispAzOptions.
const far rom char azOption3[][]
Referenced by dispAzOptions.
const far rom char azOption4[][]
Referenced by dispAzOptions.
const rom char elMenu[][]
const rom char elMenuLcd[][]
const far rom char elOption1[][]
Referenced by dispElOptions.
const far rom char elOption2[][]
Referenced by dispElOptions.
const far rom char elOption3[][]
Referenced by dispElOptions.
const far rom char elOption4[][]
Referenced by dispElOptions.
const rom char rngMenu[][]
const rom char rngMenuLcd[][]
const far rom char rngOption1[][]
Referenced by dispRngOptions.
const far rom char rngOption2[][]
Referenced by dispRngOptions.
const far rom char rngOption3[][]
Referenced by dispRngOptions.
const far rom char rngOption4[][]
Referenced by dispRngOptions.
const far rom char rngOption5[][]
Referenced by dispRngOptions.
const far rom char rngOption6[][]
Referenced by dispRngOptions.
const far rom char rngOption7[][]
Referenced by dispRngOptions.
const far rom char showTempLCDTitle[][]
const far rom char showTempLCD[][]
const far rom char showTemp1[][]
Referenced by dispTempSerialMessage.
const far rom char showTemp2[][]
Referenced by dispTempSerialMessage.
const far rom char gotoAzAngle[][]
const far rom char gotoAzAngleLCD[][]
const far rom char gotoElAngle[][]
const far rom char gotoELAngleLCD[][]
const far rom char gotoAngle2[][]
const far rom char angleStr[][]
Referenced by setValue.
const far rom char maxAzStr[][]
const far rom char maxAzSetStr[][]
const far rom char maxAz1[][]
const far rom char maxAz3[][]
const far rom char currentMinAngleStr[][]
const far rom char minAzStr[][]
const far rom char minAzSetStr[][]
const far rom char minAz1[][]
const far rom char minAz3[][]
const far rom char calibrateAngle1[][]
const far rom char maxElStr[][]
const far rom char maxElSetStr[][]
const far rom char maxEl1[][]
const far rom char maxEl3[][]
const far rom char minElStr[][]
const far rom char minElSetStr[][]
const far rom char minEl1[][]
const far rom char minEl3[][]
const far rom char minRngStr[][]
const far rom char minRngSetStr[][]
const far rom char minRngSerialStr[][]
const far rom char maxRngStr[][]
const far rom char maxRngSetStr[][]
const far rom char maxRngSerialStr[][]
void initialiseMenu(void)
Initialises the menu system.
Function: initialiseMenu(void)Include: Menusystem.hDescription: initialises the menu system so that it is fully operationalArguments: NoneReturns: None
References REMOTE, configureSerial, lcdInit, configUSER, setMenu, Root, AutoTrack, Min.
Referenced by main.
char checkForSerialInput(void)
services any user interface with the menu
Function: waitForInput(void)Include:Description: Checks the serial/local buffers for inputsArguments: NoneReturns: 1 if input has been received, 0 otherwise
References receiveCR, receiveEsc.
Referenced by serviceMenu.
void menuISR(void)
ISR function for the menu subsystem.
Function: menuISR(void)Include: Menusystem.hDescription: services any interrupts associated with the menu systemArguments: NoneReturns: None
void serviceMenu(void)
services any user interface with the menu
Function: serviceMenu(void)Include:Description: Checks if the user has made any inputs to the system. If not the function simply returns. If they have then it services the inputs, displays the correct outputs and performs the specified actionsArguments: NoneReturns: None
References REMOTE, FACTORY, checkForSerialInput, getSerialNumericInput, userEmpty, getLocalPotResult, m_currentMenu, menuStruct::minVal, menuStruct::maxVal, menuStruct::increment, menuStruct::lcdDisplayFunction, userPop, CONFIRM_CHAR, ESC_PRESSED, menuStruct::returnToPrevious, menuStruct::confirmFunction, receiveEmpty, level, SubMenu::numericFunction, receiveCR, readString, parseNumeric, receivePop, parseInput.
Referenced by main.