Menusystem.c
struct menuStruct topMenu
struct menuStruct AzMenu
struct menuStruct ElMenu
struct menuStruct RangeMenu
struct menuStruct AzGoto
Remote/Local Functions.
struct menuStruct ElGoto
struct menuStruct AzMin
struct menuStruct AzMax
struct menuStruct ElMin
struct menuStruct ElMax
struct menuStruct RngMin
struct menuStruct RngMax
struct menuStruct ShowTemp
struct menuStruct m_currentMenu
Global variable with the current menu position
Referenced by serviceMenu, setValue, setMenu, navigateAzimuthMenu, navigateRangeMenu, navigateElevationMenu, displayMenuSerial, dispSerialMessage.
userState m_userMode
Global variable with the current user mode: Local, remote or factory
void sendROM(const static rom char *romchar)
Include: Local to Menusystem.c.
File: Menusystem.c Author:Description:Duties:Functions:Created on 16 September 2014, 6:47 PM Function: sendROM(void): Transmits the given string from ROM over serialThe string to transmitReturns: None
References strcpypgm2ram, transmit.
Referenced by errOutOfRange, setValue, displayMenuSerial, dispTopOptions, dispAzOptions, dispElOptions, dispRngOptions, dispTempSerialMessage, dispSerialMessage.
void clearScreen(void)
Clears the Serial display
References height, transmit.
void sendNewLine(char length)
: Prints a number of new line ( ) characters.
References height, transmit.
Referenced by errOutOfRange, setValue, displayMenuSerial.
void filler(char length)
References transmit.
Referenced by displayMenuSerial.
void errOutOfRange(int lowerBound, int upperBound)
Description: Displays a number out of range error
References sendROM, errNumOutOfRange, transmit, intToAscii, and, sendNewLine.
Referenced by setValue, navigateTopMenu, navigateAzimuthMenu, navigateRangeMenu, navigateElevationMenu.
char * intToAscii(int num)
Description: Converts a number to a string Can only print numbers under 8 digits
Referenced by errOutOfRange, setValue, dispTempSerialMessage, dispLCDNum.
void autodisp(void)
static int parseNumeric(char *number)
parses user input string into a number
Function: parseNumeric(char *number)Include:Description: Converts ASCII input to a number, and records an error for non-numeric input, or if the number is larger than 4 digits. No number used by the user in this program will be larger than 4 digits.Arguments: The ASCII string to decodeReturns: The integer result of the string ERR_NOT_NUMERIC for any non-numeric input ERR_NUM_OUT_OF_RANGE for 0 digits or 5+ digits Function: parseNumeric(char *number)Include:Description: Calls the function which matches the user inputArguments: NoneReturns: None
References ERR_NO_NUMBER, MINUS_CHAR, ERR_NUM_OUT_OF_RANGE, ERR_NOT_NUMERIC.
Referenced by getSerialNumericInput.
int getSerialNumericInput()
Waits for input and parses number.
Function: waitForNumericInputInclude:Description: Waits in a loop for a user command ended with a new line character. Once a command is received, it is converted into the appropriate numeric value that the user has given.Arguments: NoneReturns: The integer result of the string input ERR_NOT_NUMERIC for any non-numeric input ERR_NUM_OUT_OF_RANGE for 0 digits or 5+ digits ESC_PRESSED if escape was pressed
References receiveEsc, popEsc, ESC_PRESSED, readString, parseNumeric.
Referenced by serviceMenu.
void configureTimer0(void)
References T0CON, T0CONbits.
Referenced by main.
int getLocalInputMenu(int maxStates, int(*function)(int))
int getLocalPotResult(int min, int max, int interval)
Description: Returns the value of the potentiometer on the user interface, given a maximum and minimum value, and the interval between values (eg 10-100 in multiples of 10).
References readDial.
Referenced by serviceMenu.
void setValue(int input)
Description: General funtion for menus which set values (Such as Set Max Range). This calls the appropriate function, and transmits user messages.
References sendNewLine, m_currentMenu, menuStruct::maxVal, errOutOfRange, menuStruct::minVal, menuStruct::menuNum, AZ_GOTO, Direction::azimuth, Direction::inclination, getDir, move, sendROM, angleStr, EL_GOTO, AZ_MIN, setMinAzimuthAngle, AZ_MAX, setMaxAzimuthAngle, EL_MIN, setMinElevationAngle, EL_MAX, setMaxElevationAngle, transmit, intToAscii.
void setMenu(struct menuStruct menu)
References m_currentMenu, REMOTE, FACTORY, displayMenuSerial.
Referenced by initialiseMenu, returnToTopMenu, returnToAzMenu, returnToElMenu, returnToRngMenu, navigateTopMenu, navigateAzimuthMenu, navigateRangeMenu, navigateElevationMenu.
void navigateTopMenu(int inputResult)
References setMenu, errOutOfRange.
void noFunctionNumeric(int input)
void noFunction(void)
void returnToTopMenu(void)
References setMenu.
void returnToAzMenu(void)
References setMenu.
void returnToElMenu(void)
References setMenu.
void returnToRngMenu(void)
References setMenu.
void navigateAzimuthMenu(int inputResult)
References setMenu, FACTORY, m_currentMenu, menuStruct::returnToPrevious, errOutOfRange.
void navigateElevationMenu(int inputResult)
References setMenu, FACTORY, m_currentMenu, menuStruct::returnToPrevious, errOutOfRange.
void navigateRangeMenu(int inputResult)
References setMenu, FACTORY, m_currentMenu, menuStruct::returnToPrevious, errOutOfRange.
void dispTopOptions(void)
Display the user options for the top level home menu
References sendROM, topOption1, topOption2, topOption3, topOption4, topOption5, FACTORY, topOptionCalTemp, topOptionRemote, topOptionLocal, CHOOSE.
void displayMenuSerial()
Display the current menu Title and other information over serial
References sendNewLine, filler, width, transChar, sendROM, m_currentMenu, menuStruct::lcdTitleMessage, menuStruct::serialDisplayFunction.
Referenced by setMenu.
void dispAzOptions(void)
Display the user options for the Azimuth menu
References sendROM, azOption1, azOption2, azOption3, FACTORY, azOption4, menuPrefix5, goUp, menuPrefix4, CHOOSE.
void dispElOptions(void)
Display the user options for the Azimuth menu
References sendROM, elOption1, elOption2, elOption3, FACTORY, elOption4, menuPrefix5, goUp, menuPrefix4, CHOOSE.
void dispRngOptions(void)
Display the user options for the Azimuth menu
References sendROM, rngOption1, rngOption2, FACTORY, rngOption3, rngOption4, rngOption5, rngOption6, rngOption7, menuPrefix8, goUp, menuPrefix3, CHOOSE.
void dispTempSerialMessage(void)
Display the Show Temperature serial message
References readTemp, sendROM, showTemp1, transmit, intToAscii, showTemp2.
void dispSerialMessage(void)
Display the menu serial message
References sendROM, m_currentMenu, menuStruct::serialMessage.
void dispLCDTopMenu(int option)
LCD Display Functions.
Displays the current potentiometer reading on the LCD based on the menu options contextualised by the Home menu.
References menuStruct::lcdTitleMessage, topOptionRemoteLCD.
void dispLCDAzMenu(int option)
Displays the current potentiometer reading on the LCD based on the menu options contextualised by the Azimuth menu.
References menuStruct::lcdTitleMessage.
void dispLCDElMenu(int option)
Displays the current potentiometer reading on the LCD based on the menu options contextualised by the Elevation menu.
References menuStruct::lcdTitleMessage.
void dispLCDRngMenu(int option)
Displays the current potentiometer reading on the LCD based on the menu options contextualised by the Range menu.
References menuStruct::lcdTitleMessage.
void dispLCDNum(int option)
Description: Displays the current converted value from the potentiometer onto the LCD displayArguments: The integer converted from the ADC
References intToAscii.
void initialiseMenu(void)
Initialises the menu system.
Function: initialiseMenu(void)Include: Menusystem.hDescription: initialises the menu system so that it is fully operationalArguments: NoneReturns: None
Referenced by main.
char checkForSerialInput(void)
services any user interface with the menu
Function: waitForInput(void)Include:Description: Checks the serial/local buffers for inputsArguments: NoneReturns: 1 if input has been received, 0 otherwise
References receiveCR, receiveEsc.
Referenced by serviceMenu.
void serviceMenu(void)
services any user interface with the menu
Function: serviceMenu(void)Include:Description: Checks if the user has made any inputs to the system. If not the function simply returns. If they have then it services the inputs, displays the correct outputs and performs the specified actionsArguments: NoneReturns: None
Referenced by main.