newmain.c
UPDATE_TIME
File: newmain.cAuthor: GrantDescription: Controls the main system state of the product based on a state transition type template.Created on 7 September 2014, 4:12 PM
Referenced by main.
static void initialization(systemState *state)
Function: initialization(systemState *state)Include: Local to newmain.cDescription: Initializes the system, turns on the sensors and checks if they are ready to begin workingArguments: state - The current state of the systemReturns: The next system state - At the moment always just transitions to CHECK
References configureSerial, configureTracking, configUSER, strcpypgm2ram, welcome, transmit, NEXT_STATE_PTR, SRCH.
Referenced by main.
static void transRange(void)
void configureTimer0(void)
References T0CON, T0CONbits.
Referenced by main.
void main()
Program entry point.
Function: main(void)Include: Local to newmain.cDescription: stores the current system state and manages all transitionsArguments: NoneReturns: None
References INIT, UNDEF, configureTimer0, initialiseMenu, UPDATE_TIME, serviceMenu, systemState::current, initialization, SRCH, search, TRCK, track, dispTrack, NEXT_STATE.
static void dispTrack(TrackingData target)
References newLine, transmit, TrackingData::distance, transChar, TrackingData::inclination, TrackingData::azimuth.
Referenced by main.