PanTilt.c
AZ_PWM_PIN
Referenced by panTiltISR.
IN_PWM_PIN
Referenced by panTiltISR.
DUTY_CYCLE_TIME
Referenced by delay2Direction, direction2Delay, validate.
PWM_PERIOD
Referenced by configureBase, panTiltISR.
PWM_HALF_PERIOD
Referenced by incrementFine, panTiltISR, delay2Direction, direction2Delay.
LATENCY
Referenced by incrementFine, delay2Direction, direction2Delay.
SERVO_INIT
Referenced by configureBase.
Direction calibration_offset
Direction arcRange
Delay global_delay
Referenced by panTiltISR.
signed char azimuth_angle_max
Referenced by configureBase, getMaxAzimuthAngle, setMaxAzimuthAngle.
signed char azimuth_angle_min
Referenced by configureBase, getMinAzimuthAngle, setMinAzimuthAngle.
signed char elevation_angle_max
Referenced by configureBase, getMaxElevationAngle, setMaxElevationAngle.
signed char elevation_angle_min
Referenced by configureBase, getMinElevationAngle, setMinElevationAngle.
Direction current_direction
Referenced by getDir, rawDir.
volatile char changed
Referenced by panTiltISR, updated.
static void validate(unsigned int *delay)
Function: validate(unsigned int *delay)Include: Local to PanTilt.cDescription: Limits the duration of the PDM to between 1000us and 2000usArguments: delay - a pointer to the delay variableReturns: None
References DUTY_CYCLE_TIME.
Referenced by incrementFine, direction2Delay.
static Direction delay2Direction(Delay dly)
Function: direction2Delay(DirectionState dir)Include: Local to PanTilt.cDescription: Converts an azimuth and inclination direction into a pwm periodArguments: dir - Locally defined struct containing the desired Azimuth and InclinationReturns: Delay - The required PDM delay to move the servos to the given directionRemark: This function relies on the ARC_RANGE macro being set correctly. This should hold the value of the maximum angle that the servos can be commanded
References Direction::azimuth, Delay::AzimuthDelay, DUTY_CYCLE_TIME, PWM_HALF_PERIOD, DIV_2, Direction::inclination, Delay::InclinationDelay, LATENCY.
Referenced by move, incrementFine.
static Delay direction2Delay(Direction dir)
Function: direction2Delay(DirectionState dir)Include: Local to PanTilt.cDescription: Converts an azimuth and inclination direction into a pwm periodArguments: dir - Locally defined struct containing the desired Azimuth and InclinationReturns: Delay - The required PDM delay to move the servos to the given directionRemark: This function relies on the ARC_RANGE macro being set correctly. This should hold the value of the maximum angle that the servos can be commanded
References DUTY_CYCLE_TIME, Direction::azimuth, DIV_2, Direction::inclination, validate, Delay::AzimuthDelay, PWM_HALF_PERIOD, Delay::InclinationDelay, LATENCY.
Referenced by configureBase, move.
void configureBase(void)
Function: configureBase(void)Include: PanTilt.hDescription: Configures the Pan Tilt mechanism for operationArguments: NoneReturns: NoneTodoTest that configuring the base will send it to the default location (0, 0)
References direction2Delay, INTCONbits, RCONbits, SERVO_INIT, PWM_PERIOD, azimuth_angle_max, azimuth_angle_min, elevation_angle_max, elevation_angle_min.
Referenced by configureTracking.
void move(Direction destination)
Function: move(Direction destination)Include: PanTilt.hDescription: Moves the pan tilt actuator to the specified destinationArguments: destionation - A struct containing the desired azimuth and inclinationReturns: NoneTodoPerhaps non-arbitrary wait period
References direction2Delay, delay2Direction.
Referenced by increment, track.
void increment(Direction difference)
Function: increment(Direction difference)Include: PanTilt.hDescription: Moves the pan tilt actuator to the specified destinationArguments: destionation - A struct containing the desired azimuth and inclinationReturns: None
References Direction::azimuth, Direction::inclination, move.
Referenced by search.
void incrementFine(Direction difference)
Function: incrementFine(Direction difference)Include: PanTilt.hDescription: Moves the pan tilt actuator to the specified (Relative) destinationArguments: destionation - A struct containing the desired azimuth and inclinationReturns: None
References Delay::AzimuthDelay, Direction::azimuth, PWM_HALF_PERIOD, Delay::InclinationDelay, Direction::inclination, LATENCY, validate, delay2Direction.
Direction getDir(void)
Function: getDir(void)Include: PanTilt.hDescription: returns the current position of the pan tilt mechanismArguments: NoneReturns: A struct containing the azimuth and inclination
References current_direction.
Referenced by search, track.
char getMaxAzimuthAngle(void)
Function: getMaxAzimuthAngle(void)Include: PanTilt.hDescription: returns the maximum angle of the azimuth servoArguments: NoneReturns: A char with the maximum azimuth angle.
References azimuth_angle_max.
char getMinAzimuthAngle(void)
Function: getMinAzimuthAngle(void)Include: PanTilt.hDescription: returns the minimum angle of the azimuth servoArguments: NoneReturns: A char with the minimum azimuth angle.
References azimuth_angle_min.
char getMaxElevationAngle(void)
Function: getMaxElevationAngle(void)Include: PanTilt.hDescription: returns the maximum angle of the elevation servoArguments: NoneReturns: A char with the maximum elevation angle.
References elevation_angle_max.
char getMinElevationAngle(void)
Function: getMinElevationAngle(void)Include: PanTilt.hDescription: returns the minimum angle of the elevation servoArguments: NoneReturns: A char with the minimum elevation angle.
References elevation_angle_min.
void setMaxAzimuthAngle(char p_angle)
Function: setMaxAzimuthAngle(void)Include: PanTilt.hDescription: sets the maximum angle of the azimuth servoArguments: The maximum angle (as char) to set for the azimuth servoReturns: None.
References azimuth_angle_max.
void setMinAzimuthAngle(char p_angle)
Function: setMinAzimuthAngle(void)Include: PanTilt.hDescription: sets the minimum angle of the azimuth servoArguments: The minimum angle (as char) to set for the azimuth servoReturns: None.
References azimuth_angle_min.
void setMaxElevationAngle(char p_angle)
Function: setMaxElevationAngle(void)Include: PanTilt.hDescription: sets the maximum angle of the elevation servoArguments: The maximum angle (as char) to set for the elevation servoReturns: None.
References elevation_angle_max.
void setMinElevationAngle(char p_angle)
Function: setMinElevationAngle(void)Include: PanTilt.hDescription: sets the minimum angle of the elevation servoArguments: The minimum angle (as char) to set for the elevation servoReturns: None.
References elevation_angle_min.
void calibratePanTilt(Direction reference)
Function: calibratePanTilt(Direction reference)Include: PanTilt.hDescription: Calibrates the pan tile mechanism so that any future reference to move to the reference value specified in the function call will move the pan tilt back to the current position.Arguments: reference - A struct containing the azimuth and inclinaion you wish to define as this position.Returns: NoneTodoActually write a function to calibrate the PanTilt, perhaps just offset
Direction rawDir(void)
Function: rawDir(void)Include: PanTilt.hDescription: returns the current PanTile position without calibratingArguments: NoneReturns: The position of the pan tilt without any calibrationTodoTest this
References current_direction.
void panTiltISR(void)
Function: panTiltISR(void)Include: PanTilt.hDescription: Acts as the ISR for the PanTilt moduleArguments: NoneReturns: NoneTodoEnsure that other interrupts and running functionality is not going to affect the timing here
References CCP2_INT, PWM_PERIOD, IN_PWM_PIN, global_delay, changed, Delay::InclinationDelay, Delay::AzimuthDelay, AZ_PWM_PIN, PWM_HALF_PERIOD, PIR2bits.
Referenced by lowISR, highISR.
char updated(void)
Function: updated(void)Include: PanTilt.hDescription: returns true if the last move or increment or incrementFine function has taken effect. The new direction is only loaded in at the end of the PDM, so it could take up to 0.02 seconds for the change to take effect.Arguments: delay - a pointer to the delay variableReturns: None
References changed.