Range.h
RANGE_INT
File: Range.h Author: GrantDescription: Contains the public interface for the ultrasonic module. This file contains all the external declarations, macros and global variables for using and Interfacing with the Range module.Created on 15 September 2014, 11:24 AM
Referenced by lowISR, highISR.
RANGE_H
void configureRange(void)
Function: configureRange(void)Include: Range.hDescription: Configures the Range moduleArguments: NoneReturns: None
References INIT_PIN, INTCONbits, RCONbits, readTemp, configureAD, CCP1_INPT, INIT_TRIS.
Referenced by calibrateRange, range, rangeUltrasonic, configureTracking.
void configureAD(void)
Function: configureAD(void)Include: Range.hDescription: Configures the ADC, In ADCON1, we set right-justified mode, and select AN0 as the input channel. In ADCON0, we set a sample rate of Fosc/8, select AN0, and enable the ADC. Arguments: NoneReturns: NoneTodoMake absolutely sure this works on the minimal board, and with the temperature sensor, and pot and IR sensor
References TRISA, ADCON1, ADCON0.
Referenced by configureRange.
unsigned int range(void)
Function: range(void)Include: Range.hDescription: Uses the IR and Ultrasonic sensors to find the rangeArguments: NoneReturns: fused range as an unsigned intTodoImplement the sampling rate somehow
References range, configureRange, beginUS, rangeIR, rangeUS, calibration_offset_US, calibration_offset_IR, current_target_state, CLOSE_RANGE, OUT_OF_IR, DIV_2, GOOD_TRACK, BAD_DIR, NO_TARGET, lastRange.
Referenced by rangeUS, calibrateRange, range, rangeIR, readTargetState, track.
void rangeISR(void)
Function: rangeISR(void)Include: ultrasonic.hDescription: Called when an range related interrupt is fired, acts as the service routine for the rangefinding module.Arguments: NoneReturns: None
References CCP1_INT, CCPR1, measuringUS, INIT_PIN, PIE1bits, TMR1_INT, PIR1bits, CCP1_CLEAR.
Referenced by lowISR, highISR.
void calibrateRange(signed int distance)
signed int rawRange(void)
Function: rawRange(void)Include: Range.hDescription: Returns uncalibrated range without the calibration offsetArguments: NoneReturns: distance (in mm) as an unsigned int
References lastRange.
TargetState getTargetState(void)
Function: getTargetState(void)Include: Range.hDescription: Returns the target state from the last range reading. E.g. Good track, or direction not quite correct as US returned, but IR didn't and was within IR range etc.Arguments: NoneReturns: the target state
References current_target_state.
Referenced by readTargetState.
TargetState readTargetState(void)
Function: readTargetState(void)Include: Range.hDescription: Does the same thing as getTargetState, but actually performs a range() readArguments: NoneReturns: the target state
References range, getTargetState.
Referenced by search, track.
unsigned int rangeIR(void)
Referenced by transRange.
unsigned int rangeUltrasonic(void)
Function: rangeUltrasonic(void)Include:Description: performs an ultrasonic range reading. Pins:Arguments: NoneReturns: the average of the samplestodo remove this function?
References configureRange, beginUS, rangeUS, INIT_PIN.
Referenced by transRange.