Range.c
SPD_SND
File: Range.c Author: GrantDescription: Contains all the functionality for the range module. All variables and settings concerning the range module including the the max distance, timeouts etc are private to this module. The interface functions allow all valid access to the module.Duties: -Interface to the IR and Ultrasonic sensors -Read the range from the IR and ultrasonic sensors -Fuse distances from the IR and ultrasonic sensors -Calibrate the IR and ultrasonic sensorsFunctions:Created on 15 September 2014, 11:27 AM
IR_CONV
Referenced by rangeIR.
ULTRA_CONV
NUM_IR_READS
INIT_PIN
Referenced by configureRange, beginUS, rangeISR, rangeUltrasonic.
INIT_TRIS
Referenced by configureRange.
CCP1_INPT
Referenced by configureRange.
signed int calibration_offset
volatile char measuringUS
Referenced by beginUS, rangeUS, rangeISR.
unsigned int lastRange
Referenced by rawRange, range.
signed int calibration_offset_IR
Referenced by calibrateRange, range.
signed int calibration_offset_US
Referenced by calibrateRange, range.
TargetState current_target_state
Referenced by calibrateRange, range, getTargetState.
static void beginUS(void)
Function: beginUS(void)Include: ultrasonic.hDescription: starts a scan on the ultrasonic sensorArguments: NoneReturns: None
References CCPR1H, CCPR1L, INIT_PIN, TMR1H, TMR1L, PIE1bits, measuringUS.
Referenced by calibrateRange, range, rangeUltrasonic.
unsigned int rangeIR(void)
Function: rangeIR(void)Include:Description: Reads the range from the IR SensorArguments: NoneReturns: Range (in mm) as an unsigned int.Remark: Returns 0 if there is no target foundTodoDouble check calibration and accuracy Make sure the calibration is the same every time, and does not change appreciably
References range, sampleIR, IR_CONV.
Referenced by calibrateRange, range.
static unsigned int rangeUS(unsigned char temp)
Function: rangeUS(unsigned char temp)Include: ultrasonic.hDescription: Returns the result of the ultrasonic read (zero if no target found). Will poll until measurement is complete.Arguments: tempx2 - 2x the temperature in deg CelsiusReturns: Distance in mm (unsigned int)TodoInclude temperature read (or get temperature) in Ultrasonic reading Double check the calibration and accuracy
References range, measuringUS, CCPR1, DIV_4096, DC.
Referenced by calibrateRange, range, rangeUltrasonic.
void configureRange(void)
Function: configureRange(void)Include: Range.hDescription: Configures the Range moduleArguments: NoneReturns: None
References INIT_PIN, INTCONbits, RCONbits, readTemp, configureAD, CCP1_INPT, INIT_TRIS.
Referenced by calibrateRange, range, rangeUltrasonic, configureTracking.
static unsigned int sampleIR(char numSamples)
Function: sampleIR(void)Include:Description: takes numSamples samples of the IR sensor and returns the averageArguments: NoneReturns: the average of the samplesTodoimplement the sample rate somehow
References ADC_IR_READ, ADCON0bits, ADRES.
Referenced by rangeIR.
void configureAD(void)
Function: configureAD(void)Include: Range.hDescription: Configures the ADC, In ADCON1, we set right-justified mode, and select AN0 as the input channel. In ADCON0, we set a sample rate of Fosc/8, select AN0, and enable the ADC. Arguments: NoneReturns: NoneTodoMake absolutely sure this works on the minimal board, and with the temperature sensor, and pot and IR sensor
References TRISA, ADCON1, ADCON0.
Referenced by configureRange.
void rangeISR(void)
Function: rangeISR(void)Include: ultrasonic.hDescription: Called when an range related interrupt is fired, acts as the service routine for the rangefinding module.Arguments: NoneReturns: None
References CCP1_INT, CCPR1, measuringUS, INIT_PIN, PIE1bits, TMR1_INT, PIR1bits, CCP1_CLEAR.
Referenced by lowISR, highISR.
void calibrateRange(unsigned int reference)
Function: calibrateRange(unsigned int reference)Include:Description: Calibrates the range of both the IR and ultrasonic sensors based on a given range.Arguments: reference - The distance in mm to calibrate the current measurements fromReturns: NoneTodoMake sure this works properly, and does not do bad things in different target states
References range, configureRange, beginUS, readTemp, rangeIR, rangeUS, current_target_state, NO_TARGET, CLOSE_RANGE, calibration_offset_US, GOOD_TRACK, calibration_offset_IR.
unsigned int rawRange(void)
Function: rawRange(void)Include: Range.hDescription: Returns uncalibrated range without the calibration offsetArguments: NoneReturns: distance (in mm) as an unsigned int
References lastRange.
unsigned int range(void)
Function: range(void)Include: Range.hDescription: Uses the IR and Ultrasonic sensors to find the rangeArguments: NoneReturns: fused range as an unsigned intTodoImplement the sampling rate somehow
References range, configureRange, beginUS, rangeIR, rangeUS, calibration_offset_US, calibration_offset_IR, current_target_state, CLOSE_RANGE, OUT_OF_IR, DIV_2, GOOD_TRACK, BAD_DIR, NO_TARGET, lastRange.
Referenced by rangeUS, calibrateRange, range, rangeIR, readTargetState, track.
unsigned int rangeUltrasonic(void)
Function: rangeUltrasonic(void)Include:Description: performs an ultrasonic range reading. Pins:Arguments: NoneReturns: the average of the samplestodo remove this function?
References configureRange, beginUS, rangeUS, INIT_PIN.
Referenced by transRange.
TargetState getTargetState(void)
Function: getTargetState(void)Include: Range.hDescription: Returns the target state from the last range reading. E.g. Good track, or direction not quite correct as US returned, but IR didn't and was within IR range etc.Arguments: NoneReturns: the target state
References current_target_state.
Referenced by readTargetState.
TargetState readTargetState(void)
Function: readTargetState(void)Include: Range.hDescription: Does the same thing as getTargetState, but actually performs a range() readArguments: NoneReturns: the target state
References range, getTargetState.
Referenced by search, track.