Serial.c
TX_INT_CLEAR
File: newmain.c Author: GrantDescription: Contains the functionality for the Serial module. All variables and settings concerning the serial module, such as the receive and transmit circular buffers are private to this module. The interface functions allow all valid access to the module.Duties: -Stores an received characters in the received buffer -Stores any characters to be transmitted -Transmits anything in transmit buffer via interrupts -Accessor functions for using and querying buffersFunctions:Created on 7 September 2014, 4:12 PM
Referenced by serialISR.
RC_INT_CLEAR
Referenced by serialISR.
TX_INT_ENABLE
Referenced by transmit, transChar.
RC_INT_ENABLE
TX_INT_DISABLE
Referenced by serialISR.
RC_INT_DISABLE
CR
Referenced by readString, serialISR.
NL
Referenced by serialISR.
ESC
Referenced by serialISR.
TAB
BS
Referenced by serialISR.
volatile circularBuffer receive_buffer
volatile circularBuffer transmit_buffer
volatile char carriageReturn
Referenced by configureSerial, receiveCR, readString, serialISR.
volatile char escPressed
Referenced by configureSerial, receiveEsc, popEsc, serialISR.
void configureSerial(void)
Function: configureSerial(void)Include: Serial.hDescription: Configures the serial ready for communicationArguments: NoneReturns: None
References INTCONbits, RCONbits, init, carriageReturn, escPressed, USART_TX_INT_ON, USART_RX_INT_ON, USART_BRGH_HIGH, USART_EIGHT_BIT, USART_ASYNCH_MODE.
Referenced by initialiseMenu, initialization.
void transmit(char *string)
Function: transmit(char *string)Include: Serial.hDescription: Begins transmitting the string over serial (interrupt driven)Arguments: string - pointer to the beginning of the string to transmitReturns: NoneNOTE: Must be Null Terminated! Cannot receive a literal.
References push, empty, TX_INT_ENABLE.
Referenced by sendROM, sendNewLine, clearScreen, filler, errOutOfRange, setValue, dispTempSerialMessage, stateEntry, initialization, dispTrack.
void transChar(char c)
Function: transChar(char c)Include: Serial.hDescription: Transmits a single characterArguments: c - character to transmitReturns: None
References push, TX_INT_ENABLE.
Referenced by displayMenuSerial, dispTrack.
char receiveEmpty(void)
Function: receiveEmpty(void)Include: Serial.hDescription: Indicates if the receive buffer is emptyArguments: NoneReturns: returns true if the recieve buffer is empty
References empty.
Referenced by serviceMenu.
char receivePeek(void)
Function: receivePeek(void)Include: Serial.hDescription: Returns the next character in the receive buffer without removing it from the bufferArguments: NoneReturns: The next received character
References peek.
char receivePop(void)
Function: receivePop(void)Include: Serial.hDescription: Pops the next received character from the received bufferArguments: NoneReturns: The next character from the receive buffer
References pop.
Referenced by serviceMenu.
char receiveCR(void)
Function: receiveCR(void)Include: Serial.hDescription: Indicates whether a Carriage Return has been receivedArguments: NoneReturns: non-zero if CR has been received, zero otherwise
References carriageReturn.
Referenced by checkForSerialInput, serviceMenu.
char receiveEsc(void)
Function: receiveEsc(void)Include:Description: Indicates whether an Escape character has been receivedArguments: NoneReturns: non-zero if the Esc has been received, zero otherwise
References escPressed.
Referenced by checkForSerialInput, getSerialNumericInput.
void popEsc(void)
Function: popEsc(void)Include:Description: Processes the Esc command and removes any input before the Esc command.Arguments: NoneReturns:
References empty, pop, escPressed.
Referenced by getSerialNumericInput.
void readString(char *string)
Function: readString(char *string)Include: Serial.hDescription: Writes all received data up to a carriage return into given location.Arguments: string - Pointer to location to store received dataReturns: Received data including the carriage returnRemarks: Make sure that you reserve at least BUFFERLENGTH elements at the location pointed to by string before calling this function.
References empty, pop, CR, carriageReturn.
Referenced by getSerialNumericInput, serviceMenu.
char transmitted(void)
Function: transmitted(void)Include: Serial.hDescription: returns non-zero if the message has been completely transmited e.g. if the transmit buffer is emptyArguments: NoneReturns: None
References empty.
void serialISR(void)
Function: serialISR(void)Include: Serial.hDescription: Acts as the interrupt service routine for the serial moduleArguments: NoneReturns: None
References TX_INT, empty, TX_INT_DISABLE, pop, TX_INT_CLEAR, RC_INT, peek, ESC, escPressed, BS, CR, NL, push, carriageReturn, RC_INT_CLEAR.
Referenced by lowISR, highISR.