Temp.h
TEMP_H
void configureTemp(void)
File: Temp.h Author: GrantDescription: Contains all the functionality and variables for the temp module. All unnecessary functions and variables should be shielded from the external program, and interfaced with accessor and mutator functionsContains: -Configure function -Read temperature functions -Get (last) temperature (read) function -Calibrate Temperature functionCreated on 17 September 2014, 2:16 PM Function: configureTemp(void)Include: TempDescription: Configures the temperature module for useArguments: NoneReturns: None
References TRISA, ADCON1, ADCON0.
unsigned char rawTemp(void)
Function: rawTemp(void)Include: Temp.hDescription: Returns the raw (uncalibrated temperature)Arguments: NoneReturns: Temp (in deg celsius) as an unsigned char
References DIV_2, lastTempx2.
unsigned char readTemp(void)
Function: readTemp(void)Include: Temp.hDescription: Reads the temperature from the TEMP sensorArguments: NoneReturns: Temp (in deg celsius) as an unsigned char
References readTempx2, DIV_2.
Referenced by configureRange, calibrateRange.
unsigned char readTempx2(void)
Function: readTempx2(void)Include: Temp.hDescription: Reads the temperature from the Temp sensorArguments: NoneReturns: temp x 2 (in deg celsius) as an unsigned charTodoTest and debug this function
References ADC_TEMP_READ, ADCON0bits, ADRESH, ADRESL, lastTempx2, calibration_offset.
Referenced by readTemp.
void calibrateTemp(unsigned char reference)
Function: calibrationTemp(unsigned char reference)Include: Temp.hDescription: calibrates the temperature sensor by updating the calibration offset variableArguments: reference - Reference temperature in deg CReturns: NoneNote: This function does not perform a temperature read, but uses the last value. This is because the readTemp function automatically calibrate.
References calibration_offset, DIV_2, lastTempx2.
unsigned char getTemp(void)
Function: calibrationTemp(unsigned char reference)Include: Temp.hDescription: calibrates the temperature sensor by updating the calibration offset variableArguments: reference - Reference temperature in deg CReturns: None
References DIV_2, lastTempx2.