Tracking.c
diff
File: Tracking.c Author: GrantDescription: Contains all the functionality for the Tracking Module. This module contains the functionality and algorithms used to search for, and track the target. This module makes use of PanTilt, Range and Temp modules, and configures them automatically from a call to configureTrack().Duties: -Control and coordinate Pan Tilt and range sensors -Implement searching and tracking algorithms -Predict next position of target???Functions:Created on 15 September 2014, 1:42 PM
Referenced by search.
TARGET_RAD
sampleTargetState
Referenced by track.
TIMER
static char newAngle(TargetStateData target_data)
void configureTracking(void)
References configureBase, configureRange.
Referenced by initialization.
void search(systemState *state)
References diff, getDir, Direction::azimuth, increment, Direction::inclination, readTargetState, GOOD_TRACK, NEXT_STATE_PTR, TRCK, BAD_DIR.
Referenced by main.
void trackingISR(void)
TrackingData track(systemState *state)
References getDir, Direction::azimuth, Direction::inclination, move, sampleTargetState, readTargetState, GOOD_TRACK, BAD_DIR, OUT_OF_IR, NEXT_STATE_PTR, SRCH, TrackingData::distance, range, TrackingData::azimuth, TrackingData::inclination.
Referenced by main.
static Direction prediction(Direction current)
static char newAngle(char angle, TargetStateData target_data)
References TargetStateData::centre, TargetStateData::good_tracks, TargetStateData::bad_dirs, TargetStateData::out_of_irs.