Tracking.h
TRACK_INT
File: Tracking.h Author: GrantDescription: Public interface function for the Tracking Module. This module contains the functionality and algorithms used to search for, and track the target. This module makes use of PanTilt, Range and Temp modules, and configures them automatically from a call to configureTrack().Contains: -Configure tracking -Searching algorithm -Track algorithmCreated on 15 September 2014, 1:41 PM
TRACK_H
void configureTracking(void)
References configureBase, configureRange.
Referenced by initialization.
void search(systemState *state)
References diff, getDir, Direction::azimuth, increment, Direction::inclination, readTargetState, GOOD_TRACK, NEXT_STATE_PTR, TRCK, BAD_DIR.
Referenced by main.
TrackingData track(systemState *state)
References getDir, Direction::azimuth, Direction::inclination, move, sampleTargetState, readTargetState, GOOD_TRACK, BAD_DIR, OUT_OF_IR, NEXT_STATE_PTR, SRCH, TrackingData::distance, range, TrackingData::azimuth, TrackingData::inclination.
Referenced by main.
void trackingISR(void)