User_Interface.h
USER_INT
Referenced by lowISR, highISR.
CONFIRM_CHAR
Referenced by serviceMenu, userISR.
BACK_CHAR
Referenced by userISR.
USER_H
void display(TrackingData data)
Function: display(TrackingData data)Include: User_Interface.hDescription: displays the current tracking informationArguments: data - Struct which contains all known data concerning the The position of the target. A Range of 0 indicates that no target was observed.Returns: None
void userISR(void)
Function: userISR(void)Include: User_Interface.hDescription: Acts as the ISR for the User_interface moduleArguments: NoneReturns: None
References CONFIRM_PRESS, push, CONFIRM_CHAR, BACK_PRESS, BACK_CHAR.
Referenced by lowISR, highISR.
void configUSER(void)
Function: configUSER(void)Include: User_Interface.hDescription: Configures the user interface for useArguments: NoneReturns: None
References init, configureAD, TRISB, PORTB, INTCONbits, INTCON2bits, INTCON3bits.
Referenced by initialiseMenu, initialization.
char userEmpty(void)
Function: userEmpty(void)Include: User_Interface.hDescription: returns non-zero if the user interface buffer is empty (i.e. no user input has been detected)Arguments: NoneReturns: if the user input buffer is empty
References empty.
Referenced by serviceMenu.
char userPop(void)
Function: userPop(void)Include: User_Interface.hDescription: pops a character from the user interface receive bufferArguments: NoneReturns: a character poped from the user Interface buffer
References pop.
Referenced by serviceMenu.
char userPeek(void)
Function: userPeek(void)Include: User_Interface.hDescription: returns a character in the user_Interface buffer without removing it from the bufferArguments: NoneReturns: a character in the user interface buffer
References peek.
unsigned int readDial(unsigned int max)
Function: readDial(void)Include:Description: Read the position of the dialArguments: NoneReturns: The dial position scaled by
References ADC_MAX.
Referenced by getLocalPotResult, readDialForMenu.