User_Interface.c
CONFIRM_PRESS
File: User_Interface.c Author: GrantDescription: Contains all the functionality for the User_Interface module. Works the same way as the serial module, but for the user interface.Duties: -Stores any local user input in a receive buffer -Sends display data to the LCDCreated on 15 September 2014, 1:21 PM
Referenced by userISR.
BACK_PRESS
Referenced by userISR.
ADC_MAX
Referenced by readDial.
circularBuffer receive
void display(TrackingData data)
Function: display(TrackingData data)Include: User_Interface.hDescription: displays the current tracking informationArguments: data - Struct which contains all known data concerning the The position of the target. A Range of 0 indicates that no target was observed.Returns: None
void userISR(void)
Function: userISR(void)Include: User_Interface.hDescription: Acts as the ISR for the User_interface moduleArguments: NoneReturns: None
References CONFIRM_PRESS, push, CONFIRM_CHAR, BACK_PRESS, BACK_CHAR.
Referenced by lowISR, highISR.
void configUSER(void)
Function: configUSER(void)Include: User_Interface.hDescription: Configures the user interface for useArguments: NoneReturns: None
References init, configureAD, TRISB, PORTB, INTCONbits, INTCON2bits, INTCON3bits.
Referenced by initialiseMenu, initialization.
unsigned int readDial(unsigned int max)
Function: readDial(void)Include:Description: Read the position of the dialArguments: NoneReturns: The dial position scaled by
References ADC_MAX.
Referenced by getLocalPotResult, readDialForMenu.
unsigned int readDialForMenu(unsigned int max)
Returns a value from 1 to max
References readDial.
char userEmpty(void)
Function: userEmpty(void)Include: User_Interface.hDescription: returns non-zero if the user interface buffer is empty (i.e. no user input has been detected)Arguments: NoneReturns: if the user input buffer is empty
References empty.
Referenced by serviceMenu.
char userPop(void)
Function: userPop(void)Include: User_Interface.hDescription: pops a character from the user interface receive bufferArguments: NoneReturns: a character poped from the user Interface buffer
References pop.
Referenced by serviceMenu.
char userPeek(void)
Function: userPeek(void)Include: User_Interface.hDescription: returns a character in the user_Interface buffer without removing it from the bufferArguments: NoneReturns: a character in the user interface buffer
References peek.