.TH "circularBuffer" 3 "Mon Oct 20 2014" "Version V1.0" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
circularBuffer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CircularBuffers\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBhead\fP"
.br
.ti -1c
.RI "unsigned char \fBtail\fP"
.br
.ti -1c
.RI "unsigned char \fBdata\fP [\fBBUFFERLENGTH\fP]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned char data[\fBBUFFERLENGTH\fP]"

.SS "unsigned char head"

.SS "unsigned char tail"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
