.TH "Delay" 3 "Tue Oct 21 2014" "Version V1.0" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Delay \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "signed int \fBAzimuthDelay\fP"
.br
.ti -1c
.RI "signed int \fBInclinationDelay\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file PanTilt\&.c\&.
.SH "Field Documentation"
.PP 
.SS "signed int AzimuthDelay"

.PP
Definition at line 16 of file PanTilt\&.c\&.
.SS "signed int InclinationDelay"

.PP
Definition at line 17 of file PanTilt\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
