.TH "Direction" 3 "Mon Oct 20 2014" "Version V1.0" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Direction \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Common\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBazimuth\fP"
.br
.ti -1c
.RI "int \fBinclination\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int azimuth"

.SS "int inclination"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
