.TH "LCD.h" 3 "Tue Oct 21 2014" "Version V1.0" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LCD.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBconfigLCD\fP (void)"
.br
.ti -1c
.RI "void \fBdisplayLCD\fP (char *string)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void configLCD (void)"

.PP
Definition at line 23 of file LCD\&.c\&.
.SS "void displayLCD (char *string)"

.PP
 Function: \fBdisplayLCD(char *string)\fP
.PP
Include: \fBLCD\&.h\fP
.PP
Description: Displays the given string on the LCD
.PP
Arguments: string - pointer to the data to display
.PP
Returns: None 
.PP
Definition at line 39 of file LCD\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
