.TH "Yavin4DefenceSystem/Code/LCD.c" 3 "Sun Oct 26 2014" "Version V1.1" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Yavin4DefenceSystem/Code/LCD.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Common\&.h'\fP
.br
\fC#include 'LCD_defs\&.h'\fP
.br
\fC#include <delays\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdelay\fP (unsigned int t)"
.br
.RI "\fIInclude: \fP"
.ti -1c
.RI "char \fBlcdBusy\fP (void)"
.br
.RI "\fIInclude: \fP"
.ti -1c
.RI "void \fBlcdWrite\fP (unsigned char byte, unsigned char mode)"
.br
.RI "\fIInclude: \fBLCD\&.h\fP\&. \fP"
.ti -1c
.RI "void \fBlcdInit\fP (void)"
.br
.RI "\fIInitialises the LCD so that it can be used\&. \fP"
.ti -1c
.RI "void \fBlcdWriteString\fP (char *string, char line)"
.br
.RI "\fIInclude: \fBLCD\&.h\fP\&. \fP"
.ti -1c
.RI "void \fBlcdWriteChar\fP (char byte, char line, char column)"
.br
.RI "\fIFeed character, line (1 or 2), and column(1-16) \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "void delay (unsigned intt)"

.PP
Include: 
.PP
 File: \fBUser_Interface\&.c\fP Author:
.PP
Description: Contains all the interface to the LCD hardware
.PP
Duties: -Interfaces with and controls the LCD -Displays data on the LCD
.PP
\fBTodo\fP
.RS 4
Complete, test, debug and document this code!!!
.RE
.PP
.PP
Created on 15 September 2014, 1:21 PM
.PP
.PP
 Function: delay(void)
.PP
Description:around 2 ms delay function for the proper delay added after specific commands.
.PP
Arguments: t -
.PP
Returns: None 
.SS "char lcdBusy (void)"

.PP
Include: 
.PP
 Function: \fBlcdBusy(void)\fP
.PP
Description: check the busy flag(DB7) of the LCD,when 0, it means the LCD is not busy and ready to receive data
.PP
Arguments: None
.PP
Returns: None Set data lines to input
.PP
Set the enable low, ensure clock signal is low
.PP
Set RW to read read from LCD
.PP
Set the register select to low for instruction
.PP
Set the enable high, ensure clock signal is high to allow data transmission
.PP
Set control lines to output
.PP
Set data lines to output
.PP
Set enable low to allow data to flow through
.PP
Set control lines to output
.PP
Set data lines to output
.PP
Set enable low to allow data to flow through 
.SS "void lcdInit (void)"

.PP
Initialises the LCD so that it can be used\&. Feed character, line (1 or 2), and column(1-16)
.PP
.PP
 Function: \fBlcdInit(void)\fP
.PP
Include: \fBLCD\&.h\fP
.PP
Description: Initialises the LCD hardware so that data can be displayed on the LCD in local interface mode
.PP
Arguments: None
.PP
Returns: None Set data lines to output
.PP
Set control lines low
.PP
8 bits, 2 lines, 5x7 dots, 0x38
.PP
Display on, cursor off, blinking off (Z, 0x0F)
.PP
Cursor moves right?, display not shift (Z, 0x04)
.PP
Clear display 
.SS "void lcdWrite (unsigned charbyte, unsigned charmode)"

.PP
Include: \fBLCD\&.h\fP\&. 
.PP
 Function: \fBlcdWrite(unsigned char byte, unsigned char mode)\fP
.PP
Description: the write enable function for LCD, send the data or commands to LCD and enable the LCD to do and write.
.PP
Arguments: byte - mode -
.PP
Returns: None Set data lines to output
.PP
Write data to data lines
.PP
Set clock high
.PP
Set clock low 
.SS "void lcdWriteChar (charbyte, charline, charcolumn)"

.PP
Feed character, line (1 or 2), and column(1-16) Feed character string, and line (1 or 2)
.PP
.PP
 Function: lcdWriteChar(unsigned char byte, unsigned char line, unsigned char column)
.PP
Include: \fBLCD\&.h\fP
.PP
Description: write a single character to LCD on the specific location(which line and which column)
.PP
Arguments: byte - line - column -
.PP
Returns: NoneFeed character, line (1 or 2), and column(1-16) 
.SS "void lcdWriteString (char *string, charline)"

.PP
Include: \fBLCD\&.h\fP\&. 
.PP
 Function: lcdWriteString(char *string, unsigned char line)
.PP
Description: Write the string to the LCD on the specific line.
.PP
Arguments: string - line -
.PP
Returns: NoneFeed character string, and line (1 or 2) Also include information about which row 
.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
