.TH "LCD.h" 3 "Tue Oct 21 2014" "Version V1.0" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LCD.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLCD_H\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBconfigLCD\fP (void)"
.br
.ti -1c
.RI "void \fBdisplayLCD\fP (char *string)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LCD_H"

.PP
Definition at line 18 of file LCD\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void configLCD (void)"

.PP
 File: \fBLCD\&.h\fP Author: Grant
.PP
Description: Contains the public interface for the LCD module\&.
.PP
Created on 17 September 2014, 9:01 PM
.PP
.PP
 File: \fBUser_Interface\&.c\fP Author: Grant
.PP
Description: Contains all the interface to the LCD hardware
.PP
Duties: -Interfaces with and controls the LCD -Displays data on the LCD
.PP
Created on 15 September 2014, 1:21 PM 
.PP
Definition at line 28 of file LCD\&.c\&.
.SS "void displayLCD (char *string)"

.PP
 Function: \fBdisplayLCD(char *string)\fP
.PP
Include: \fBLCD\&.h\fP
.PP
Description: Displays the given string on the LCD
.PP
Arguments: string - pointer to the data to display
.PP
Returns: None 
.PP
Definition at line 44 of file LCD\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
