.TH "Yavin4DefenceSystem/Code/LCD.h" 3 "Sun Oct 26 2014" "Version V1.1" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Yavin4DefenceSystem/Code/LCD.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLCD_H\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlcdWriteString\fP (char *string, char line)"
.br
.RI "\fIInclude: \fBLCD\&.h\fP\&. \fP"
.ti -1c
.RI "void \fBlcdWriteChar\fP (char byte, char line, char column)"
.br
.RI "\fIFeed character string, and line (1 or 2) \fP"
.ti -1c
.RI "void \fBlcdInit\fP (void)"
.br
.RI "\fIFeed character, line (1 or 2), and column(1-16) \fP"
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LCD_H"

.SH "Function Documentation"
.PP 
.SS "void lcdInit (void)"

.PP
Feed character, line (1 or 2), and column(1-16) Feed character, line (1 or 2), and column(1-16)
.PP
.PP
 Function: \fBlcdInit(void)\fP
.PP
Include: \fBLCD\&.h\fP
.PP
Description: Initialises the LCD hardware so that data can be displayed on the LCD in local interface mode
.PP
Arguments: None
.PP
Returns: None Set data lines to output
.PP
Set control lines low
.PP
8 bits, 2 lines, 5x7 dots, 0x38
.PP
Display on, cursor off, blinking off (Z, 0x0F)
.PP
Cursor moves right?, display not shift (Z, 0x04)
.PP
Clear display 
.SS "void lcdWriteChar (charbyte, charline, charcolumn)"

.PP
Feed character string, and line (1 or 2) Feed character string, and line (1 or 2)
.PP
.PP
 Function: lcdWriteChar(unsigned char byte, unsigned char line, unsigned char column)
.PP
Include: \fBLCD\&.h\fP
.PP
Description: Write the character data to the specific location on the LCD screen.
.PP
Arguments: byte - character written to LCD  line - line 1 or 2 column - col 1-16
.PP
Returns: NoneFeed character, line (1 or 2), and column(1-16) 
.SS "void lcdWriteString (char *string, charline)"

.PP
Include: \fBLCD\&.h\fP\&. 
.PP
 File: \fBLCD\&.h\fP Author: Grant
.PP
Description: Contains the public interface for the LCD module\&.
.PP
Created on 17 September 2014, 9:01 PM
.PP
.PP
 Function: lcdWriteString(char *string, unsigned char line)
.PP
Description: Write the string on the specific line on the LCD screen
.PP
Arguments: string - string written to LCD line - location of the string on the LCD screen.
.PP
Returns: NoneFeed character string, and line (1 or 2) Also include information about which row 
.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
