.TH "LCD.c" 3 "Tue Oct 21 2014" "Version V1.0" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LCD.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Common\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBconfigLCD\fP (void)"
.br
.ti -1c
.RI "void \fBdisplayLCD\fP (char *string)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void configLCD (void)"

.PP
 File: \fBUser_Interface\&.c\fP Author: Grant
.PP
Description: Contains all the interface to the LCD hardware
.PP
Created on 15 September 2014, 1:21 PM 
.PP
Definition at line 23 of file LCD\&.c\&.
.SS "void displayLCD (char *string)"

.PP
 Function: \fBdisplayLCD(char *string)\fP
.PP
Include: \fBLCD\&.h\fP
.PP
Description: Displays the given string on the LCD
.PP
Arguments: string - pointer to the data to display
.PP
Returns: None 
.PP
Definition at line 39 of file LCD\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
