.TH "C:/Users/Grant/Documents/GitHub/Yavin4DefenceSystem/Code/newmain.c" 3 "Wed Oct 22 2014" "Version V1.1" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Grant/Documents/GitHub/Yavin4DefenceSystem/Code/newmain.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Common\&.h'\fP
.br
\fC#include 'Tracking\&.h'\fP
.br
\fC#include 'Range\&.h'\fP
.br
\fC#include 'User_Interface\&.h'\fP
.br
\fC#include 'Serial\&.h'\fP
.br
\fC#include 'PanTilt\&.h'\fP
.br
\fC#include 'Menusystem\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmain\fP ()"
.br
.RI "\fIProgram entry point\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "void main ()"

.PP
Program entry point\&. 
.PP
 Function: \fBmain(void)\fP
.PP
Include: Local to \fBnewmain\&.c\fP
.PP
Description: stores the current system state and manages all transitions
.PP
Arguments: None
.PP
Returns: None 
.PP
Definition at line 44 of file newmain\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
