.TH "Yavin4DefenceSystem/Code/newmain.c" 3 "Sun Oct 26 2014" "Version V1.1" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Yavin4DefenceSystem/Code/newmain.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Common\&.h'\fP
.br
\fC#include 'Tracking\&.h'\fP
.br
\fC#include 'Range\&.h'\fP
.br
\fC#include 'User_Interface\&.h'\fP
.br
\fC#include 'Serial\&.h'\fP
.br
\fC#include 'PanTilt\&.h'\fP
.br
\fC#include 'Menusystem\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUPDATE_TIME\fP   1000"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBinitialization\fP (\fBsystemState\fP *state)"
.br
.ti -1c
.RI "static void \fBtransRange\fP (void)"
.br
.ti -1c
.RI "void \fBconfigureTimer0\fP (void)"
.br
.ti -1c
.RI "void \fBmain\fP ()"
.br
.RI "\fIProgram entry point\&. \fP"
.ti -1c
.RI "static void \fBdispTrack\fP (\fBTrackingData\fP target)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define UPDATE_TIME   1000"

.PP
 File: \fBnewmain\&.c\fP
.PP
Author: Grant
.PP
Description: Controls the main system state of the product based on a state transition type template\&.
.PP
Created on 7 September 2014, 4:12 PM 
.SH "Function Documentation"
.PP 
.SS "void configureTimer0 (void)"

.SS "static void dispTrack (\fBTrackingData\fPtarget)\fC [static]\fP"

.SS "static void initialization (\fBsystemState\fP *state)\fC [static]\fP"

.PP
 Function: \fBinitialization(systemState *state)\fP
.PP
Include: Local to \fBnewmain\&.c\fP
.PP
Description: Initializes the system, turns on the sensors and checks if they are ready to begin working
.PP
Arguments: state - The current state of the system
.PP
Returns: The next system state - At the moment always just transitions to CHECK 
.SS "void main (void)"

.PP
Program entry point\&. 
.PP
 Function: \fBmain(void)\fP
.PP
Include: Local to \fBnewmain\&.c\fP
.PP
Description: stores the current system state and manages all transitions
.PP
Arguments: None
.PP
Returns: None 
.SS "static void transRange (void)\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
