.TH "Range.c" 3 "Mon Oct 20 2014" "Version V1.0" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Range.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Common\&.h'\fP
.br
\fC#include 'Temp\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSPD_SND\fP(T)   (\fBDIV_1024\fP(T * (unsigned int)614) + 331)"
.br
.ti -1c
.RI "#define \fBIR_CONV\fP(ad)   ((unsigned long)135174 / (ad) - 28)"
.br
.ti -1c
.RI "#define \fBULTRA_CONV\fP(tme, T)   \fBDIV_65536\fP(tme * (unsigned long)(\fBDIV_65536\fP((unsigned long)519078 * T) + (unsigned long)4362)) - 18"
.br
.ti -1c
.RI "#define \fBNUM_IR_READS\fP   10"
.br
.ti -1c
.RI "#define \fBINIT_PIN\fP   \fBPORTCbits\&.RC3\fP"
.br
.ti -1c
.RI "#define \fBINIT_TRIS\fP   \fBTRISCbits\&.RC3\fP"
.br
.ti -1c
.RI "#define \fBCCP1_INPT\fP   \fBTRISCbits\&.RC2\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned int \fBrangeIR\fP (void)"
.br
.ti -1c
.RI "void \fBconfigureRange\fP (void)"
.br
.ti -1c
.RI "void \fBconfigureAD\fP (void)"
.br
.ti -1c
.RI "void \fBrangeISR\fP (void)"
.br
.ti -1c
.RI "void \fBcalibrateRange\fP (unsigned int reference)"
.br
.ti -1c
.RI "unsigned int \fBrawRange\fP (void)"
.br
.ti -1c
.RI "unsigned int \fBrange\fP (void)"
.br
.ti -1c
.RI "unsigned int \fBrangeUltrasonic\fP (void)"
.br
.ti -1c
.RI "\fBTargetState\fP \fBgetTargetState\fP (void)"
.br
.ti -1c
.RI "\fBTargetState\fP \fBreadTargetState\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CCP1_INPT   \fBTRISCbits\&.RC2\fP"

.SS "#define INIT_PIN   \fBPORTCbits\&.RC3\fP"

.SS "#define INIT_TRIS   \fBTRISCbits\&.RC3\fP"

.SS "#define IR_CONV(ad)   ((unsigned long)135174 / (ad) - 28)"

.SS "#define NUM_IR_READS   10"

.SS "#define SPD_SND(T)   (\fBDIV_1024\fP(T * (unsigned int)614) + 331)"

.SS "#define ULTRA_CONV(tme, T)   \fBDIV_65536\fP(tme * (unsigned long)(\fBDIV_65536\fP((unsigned long)519078 * T) + (unsigned long)4362)) - 18"

.SH "Function Documentation"
.PP 
.SS "void calibrateRange (unsigned intreference)"

.PP
 Function: \fBcalibrateRange(unsigned int reference)\fP
.PP
Include:
.PP
Description: Calibrates the range of both the IR and ultrasonic sensors based on a given range\&.
.PP
Arguments: reference - The distance in mm to calibrate the current measurements from
.PP
Returns: None 
.SS "void configureAD (void)"

.PP
 Function: \fBconfigureAD(void)\fP
.PP
Include: \fBRange\&.h\fP
.PP
Description: Configures the ADC, In ADCON1, we set right-justified mode, and select AN0 as the input channel\&. In ADCON0, we set a sample rate of Fosc/8, select AN0, and enable the ADC\&. Arguments: None
.PP
Returns: None 
.SS "void configureRange (void)"

.PP
 Function: \fBconfigureRange(void)\fP
.PP
Include: \fBRange\&.h\fP
.PP
Description: Configures the Range module
.PP
Arguments: None
.PP
Returns: None 
.SS "\fBTargetState\fP getTargetState (void)"

.PP
 Function: \fBgetTargetState(void)\fP
.PP
Include: \fBRange\&.h\fP
.PP
Description: Returns the target state from the last range reading\&. E\&.g\&. Good track, or direction not quite correct as US returned, but IR didn't and was within IR range etc\&.
.PP
Arguments: None
.PP
Returns: the target state 
.SS "unsigned int range (void)"

.PP
 Function: \fBrange()\fP
.PP
Include:
.PP
Description: Uses the IR and Ultrasonic sensors to find the range
.PP
Arguments: None
.PP
Returns: None 
.SS "unsigned int rangeIR (void)"

.PP
 Function: \fBrangeIR(void)\fP
.PP
Include:
.PP
Description: Reads the range from the IR Sensor
.PP
Arguments: None
.PP
Returns: Range (in mm) as an unsigned int\&.
.PP
Remark: Returns 0 if there is no target found 
.SS "void rangeISR (void)"

.PP
 Function: \fBrangeISR(void)\fP
.PP
Include: ultrasonic\&.h
.PP
Description: Called when an range related interrupt is fired, acts as the service routine for the rangefinding module\&.
.PP
Arguments: None
.PP
Returns: None 
.SS "unsigned int rangeUltrasonic (void)"

.PP
 Function: rangeUS(void)
.PP
Include:
.PP
Description: performs an ultrasonic range reading\&. Pins:
.PP
Arguments: None
.PP
Returns: the average of the samples 
.SS "unsigned int rawRange (void)"

.PP
 Function: speed_sound(unsigned char tempx2)
.PP
Include:
.PP
Description: Returns the calibration offset to calculate the raw data
.PP
Arguments: None
.PP
Returns: None 
.SS "\fBTargetState\fP readTargetState (void)"

.PP
 Function: \fBreadTargetState(void)\fP
.PP
Include: \fBRange\&.h\fP
.PP
Description: Does the same thing as getTargetState, but actually performs a \fBrange()\fP read
.PP
Arguments: None
.PP
Returns: the target state 
.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
