.TH "Yavin4DefenceSystem/Code/Range.h" 3 "Sun Oct 26 2014" "Version V1.1" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Yavin4DefenceSystem/Code/Range.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRANGE_INT\fP   \fBCCP1_INT\fP | \fBTMR1_INT\fP"
.br
.ti -1c
.RI "#define \fBRANGE_H\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBconfigureRange\fP (void)"
.br
.ti -1c
.RI "void \fBconfigureAD\fP (void)"
.br
.ti -1c
.RI "unsigned int \fBrange\fP (void)"
.br
.RI "\fISamples the range\&. \fP"
.ti -1c
.RI "void \fBrangeISR\fP (void)"
.br
.ti -1c
.RI "void \fBcalibrateRange\fP (signed int distance)"
.br
.ti -1c
.RI "signed int \fBrawRange\fP (void)"
.br
.ti -1c
.RI "\fBTargetState\fP \fBgetTargetState\fP (void)"
.br
.ti -1c
.RI "\fBTargetState\fP \fBreadTargetState\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RANGE_H"

.SS "#define RANGE_INT   \fBCCP1_INT\fP | \fBTMR1_INT\fP"

.PP
 File: \fBRange\&.h\fP Author: Grant
.PP
Description: Contains the public interface for the ultrasonic module\&. This file contains all the external declarations, macros and global variables for using and Interfacing with the Range module\&.
.PP
Created on 15 September 2014, 11:24 AM 
.SH "Function Documentation"
.PP 
.SS "void calibrateRange (signed intdistance)"

.SS "void configureAD (void)"

.PP
 Function: \fBconfigureAD(void)\fP
.PP
Include: \fBRange\&.h\fP
.PP
Description: Configures the ADC, In ADCON1, we set right-justified mode, and select AN0 as the input channel\&. In ADCON0, we set a sample rate of Fosc/8, select AN0, and enable the ADC\&. Arguments: None
.PP
Returns: None 
.SS "void configureRange (void)"

.PP
 Function: \fBconfigureRange(void)\fP
.PP
Include: \fBRange\&.h\fP
.PP
Description: Configures the Range module
.PP
Arguments: None
.PP
Returns: None 
.SS "\fBTargetState\fP getTargetState (void)"

.PP
 Function: \fBgetTargetState(void)\fP
.PP
Include: \fBRange\&.h\fP
.PP
Description: Returns the target state from the last range reading\&. E\&.g\&. Good track, or direction not quite correct as US returned, but IR didn't and was within IR range etc\&.
.PP
Arguments: None
.PP
Returns: the target state 
.SS "unsigned int range (void)"

.PP
Samples the range\&. 
.PP
 Function: \fBrange(void)\fP
.PP
Include: \fBRange\&.h\fP
.PP
Description: Takes a number of samples of the ultrasonic sensor at a specified rate\&. Continues to sample the IR sensor at a different rate while sampling the ultrasonic\&. Then combines the ranges and sets the target state
.PP
Arguments: None
.PP
Returns: the range Standard room temperature for now
.PP
\fBTodo\fP
.RS 4
Read in temperature for US calculation 
.RE
.PP

.SS "void rangeISR (void)"

.PP
 Function: \fBrangeISR(void)\fP
.PP
Include: ultrasonic\&.h
.PP
Description: Called when an range related interrupt is fired, acts as the service routine for the rangefinding module\&.
.PP
Arguments: None
.PP
Returns: None 
.SS "signed int rawRange (void)"

.PP
 Function: speed_sound(unsigned char tempx2)
.PP
Include:
.PP
Description: Returns the calibration offset to calculate the raw data
.PP
Arguments: None
.PP
Returns: None 
.SS "\fBTargetState\fP readTargetState (void)"

.PP
 Function: \fBreadTargetState(void)\fP
.PP
Include: \fBRange\&.h\fP
.PP
Description: Does the same thing as getTargetState, but actually performs a \fBrange()\fP read
.PP
Arguments: None
.PP
Returns: the target state 
.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
