.TH "Serial.c" 3 "Tue Oct 21 2014" "Version V1.0" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Serial.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Common\&.h'\fP
.br
\fC#include <usart\&.h>\fP
.br
\fC#include 'CircularBuffers\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTX_INT_CLEAR\fP()   \fBPIR1bits\&.TXIF\fP = 0"
.br
.ti -1c
.RI "#define \fBRC_INT_CLEAR\fP()   \fBPIR1bits\&.RCIF\fP = 0"
.br
.ti -1c
.RI "#define \fBTX_INT_ENABLE\fP()   \fBTX_INT_CLEAR\fP(); \fBPIE1bits\&.TXIE\fP = 1"
.br
.ti -1c
.RI "#define \fBRC_INT_ENABLE\fP()   \fBRC_INT_CLEAR\fP(); \fBPIE1bits\&.RCIE\fP = 1"
.br
.ti -1c
.RI "#define \fBTX_INT_DISABLE\fP()   \fBPIE1bits\&.TXIE\fP = 0"
.br
.ti -1c
.RI "#define \fBRC_INT_DISABLE\fP()   \fBPIE1bits\&.RCIE\fP = 0"
.br
.ti -1c
.RI "#define \fBCR\fP   0x0D"
.br
.ti -1c
.RI "#define \fBNL\fP   0x0A"
.br
.ti -1c
.RI "#define \fBESC\fP   0x1B"
.br
.ti -1c
.RI "#define \fBTAB\fP   0x09"
.br
.ti -1c
.RI "#define \fBBS\fP   0x07"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBconfigureSerial\fP (void)"
.br
.ti -1c
.RI "void \fBtransmit\fP (char *string)"
.br
.ti -1c
.RI "void \fBtransChar\fP (char c)"
.br
.ti -1c
.RI "char \fBreceiveEmpty\fP (void)"
.br
.ti -1c
.RI "char \fBreceivePeek\fP (void)"
.br
.ti -1c
.RI "char \fBreceivePop\fP (void)"
.br
.ti -1c
.RI "char \fBreceiveCR\fP (void)"
.br
.ti -1c
.RI "void \fBreadString\fP (char *string)"
.br
.ti -1c
.RI "char \fBtransmitted\fP (void)"
.br
.ti -1c
.RI "void \fBserialISR\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BS   0x07"

.PP
Definition at line 39 of file Serial\&.c\&.
.SS "#define CR   0x0D"

.PP
Definition at line 35 of file Serial\&.c\&.
.SS "#define ESC   0x1B"

.PP
Definition at line 37 of file Serial\&.c\&.
.SS "#define NL   0x0A"

.PP
Definition at line 36 of file Serial\&.c\&.
.SS "#define RC_INT_CLEAR()   \fBPIR1bits\&.RCIF\fP = 0"

.PP
Definition at line 28 of file Serial\&.c\&.
.SS "#define RC_INT_DISABLE()   \fBPIE1bits\&.RCIE\fP = 0"

.PP
Definition at line 32 of file Serial\&.c\&.
.SS "#define RC_INT_ENABLE()   \fBRC_INT_CLEAR\fP(); \fBPIE1bits\&.RCIE\fP = 1"

.PP
Definition at line 30 of file Serial\&.c\&.
.SS "#define TAB   0x09"

.PP
Definition at line 38 of file Serial\&.c\&.
.SS "#define TX_INT_CLEAR()   \fBPIR1bits\&.TXIF\fP = 0"

.PP
 File: \fBnewmain\&.c\fP Author: Grant
.PP
Description: Contains the functionality for the Serial module\&. All variables and settings concerning the serial module, such as the receive and transmit circular buffers are private to this module\&. The interface functions allow all valid access to the module\&.
.PP
Duties: -Stores an received characters in the received buffer -Stores any characters to be transmitted -Transmits anything in transmit buffer via interrupts -Accessor functions for using and querying buffers
.PP
Functions:
.PP
Created on 7 September 2014, 4:12 PM 
.PP
Definition at line 27 of file Serial\&.c\&.
.SS "#define TX_INT_DISABLE()   \fBPIE1bits\&.TXIE\fP = 0"

.PP
Definition at line 31 of file Serial\&.c\&.
.SS "#define TX_INT_ENABLE()   \fBTX_INT_CLEAR\fP(); \fBPIE1bits\&.TXIE\fP = 1"

.PP
Definition at line 29 of file Serial\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void configureSerial (void)"

.PP
 Function: \fBconfigureSerial(void)\fP
.PP
Include: \fBSerial\&.h\fP
.PP
Description: Configures the serial ready for communication
.PP
Arguments: None
.PP
Returns: None 
.PP
Definition at line 57 of file Serial\&.c\&.
.SS "void readString (char *string)"

.PP
 Function: \fBreadString(char *string)\fP
.PP
Include: \fBSerial\&.h\fP
.PP
Description: Writes all received data up to a carriage return into given location\&.
.PP
Arguments: string - Pointer to location to store received data
.PP
Returns: Received data up to a carriage return
.PP
Remarks: Make sure that you reserve at least BUFFERLENGTH elements at the location pointed to by string before calling this function\&. 
.PP
Definition at line 206 of file Serial\&.c\&.
.SS "char receiveCR (void)"

.PP
 Function: \fBreceiveCR(void)\fP
.PP
Include: \fBSerial\&.h\fP
.PP
Description: Indicates whether a Carriage Return has been received
.PP
Arguments: None
.PP
Returns: non-zero if CR has been received, zero otherwise 
.PP
Definition at line 186 of file Serial\&.c\&.
.SS "char receiveEmpty (void)"

.PP
 Function: \fBreceiveEmpty(void)\fP
.PP
Include: \fBSerial\&.h\fP
.PP
Description: Indicates if the receive buffer is empty
.PP
Arguments: None
.PP
Returns: returns true if the recieve buffer is empty 
.PP
Definition at line 136 of file Serial\&.c\&.
.SS "char receivePeek (void)"

.PP
 Function: \fBreceivePeek(void)\fP
.PP
Include: \fBSerial\&.h\fP
.PP
Description: Returns the next character in the receive buffer without removing it from the buffer
.PP
Arguments: None
.PP
Returns: The next received character 
.PP
Definition at line 153 of file Serial\&.c\&.
.SS "char receivePop (void)"

.PP
 Function: \fBreceivePop(void)\fP
.PP
Include: \fBSerial\&.h\fP
.PP
Description: Pops the next received character from the received buffer
.PP
Arguments: None
.PP
Returns: The next character from the receive buffer 
.PP
Definition at line 169 of file Serial\&.c\&.
.SS "void serialISR (void)"

.PP
 Function: \fBserialISR(void)\fP
.PP
Include: \fBSerial\&.h\fP
.PP
Description: Acts as the interrupt service routine for the serial module
.PP
Arguments: None
.PP
Returns: None 
.PP
Definition at line 248 of file Serial\&.c\&.
.SS "void transChar (charc)"

.PP
 Function: \fBtransChar(char c)\fP
.PP
Include: \fBSerial\&.h\fP
.PP
Description: Transmits a single character
.PP
Arguments: c - character to transmit
.PP
Returns: None 
.PP
Definition at line 116 of file Serial\&.c\&.
.SS "void transmit (char *string)"

.PP
 Function: \fBtransmit(char *string)\fP
.PP
Include: \fBSerial\&.h\fP
.PP
Description: Begins transmitting the string over serial (interrupt driven)
.PP
Arguments: string - pointer to the beginning of the string to transmit
.PP
Returns: None
.PP
NOTE: Must be Null Terminated! Cannot receive a literal\&. 
.PP
Definition at line 90 of file Serial\&.c\&.
.SS "char transmitted (void)"

.PP
 Function: \fBtransmitted(void)\fP
.PP
Include: \fBSerial\&.h\fP
.PP
Description: returns non-zero if the message has been completely transmited e\&.g\&. if the transmit buffer is empty
.PP
Arguments: None
.PP
Returns: None 
.PP
Definition at line 232 of file Serial\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
