.TH "SubMenu" 3 "Mon Oct 20 2014" "Version V1.0" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SubMenu \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBserialMessage\fP [\fBMAX_SER_MSG_LEN\fP]"
.br
.ti -1c
.RI "char \fBlcdMessage\fP [\fBMAX_LCD_MSG_LEN\fP]"
.br
.ti -1c
.RI "char \fBserialOptions\fP [\fBMAX_NUM_OPTIONS\fP]"
.br
.ti -1c
.RI "char \fBinptOptions\fP [\fBMAX_NUM_OPTIONS\fP]"
.br
.ti -1c
.RI "void(* \fBnumericFunction\fP )(int)"
.br
.ti -1c
.RI "void(* \fBdefaultFunction\fP )(void)"
.br
.ti -1c
.RI "struct \fBSubMenu\fP * \fBsubMenues\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void(* defaultFunction)(void)"

.SS "char inptOptions[\fBMAX_NUM_OPTIONS\fP]"

.SS "char lcdMessage[\fBMAX_LCD_MSG_LEN\fP]"

.SS "void(* numericFunction)(int)"

.SS "char serialMessage[\fBMAX_SER_MSG_LEN\fP]"

.SS "char serialOptions[\fBMAX_NUM_OPTIONS\fP]"

.SS "struct \fBSubMenu\fP* subMenues"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
