.TH "systemState" 3 "Tue Oct 21 2014" "Version V1.0" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
systemState \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Common\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBpossible_states\fP \fBcurrent\fP"
.br
.ti -1c
.RI "\fBpossible_states\fP \fBprevious\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 64 of file Common\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBpossible_states\fP current"

.PP
Definition at line 65 of file Common\&.h\&.
.SS "\fBpossible_states\fP previous"

.PP
Definition at line 66 of file Common\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
