.TH "Temp.c" 3 "Mon Oct 20 2014" "Version V1.0" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Temp.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Common\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBconfigureTemp\fP (void)"
.br
.ti -1c
.RI "unsigned char \fBreadTempx2\fP (void)"
.br
.ti -1c
.RI "unsigned char \fBreadTemp\fP (void)"
.br
.ti -1c
.RI "unsigned char \fBrawTemp\fP (void)"
.br
.ti -1c
.RI "void \fBcalibrateTemp\fP (unsigned char reference)"
.br
.ti -1c
.RI "unsigned char \fBgetTemp\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void calibrateTemp (unsigned charreference)"

.SS "void configureTemp (void)"

.SS "unsigned char getTemp (void)"

.SS "unsigned char rawTemp (void)"

.SS "unsigned char readTemp (void)"

.SS "unsigned char readTempx2 (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
