.TH "Yavin4DefenceSystem/Code/Temp.c" 3 "Sun Oct 26 2014" "Version V1.1" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Yavin4DefenceSystem/Code/Temp.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Common\&.h'\fP
.br
\fC#include 'Range\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBconfigureTemp\fP (void)"
.br
.ti -1c
.RI "unsigned char \fBreadTempx2\fP (void)"
.br
.ti -1c
.RI "unsigned char \fBreadTemp\fP (void)"
.br
.ti -1c
.RI "unsigned char \fBrawTemp\fP (void)"
.br
.ti -1c
.RI "void \fBcalibrateTemp\fP (unsigned char reference)"
.br
.ti -1c
.RI "unsigned char \fBgetTemp\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static signed char \fBcalibration_offset\fP = 0"
.br
.ti -1c
.RI "static unsigned char \fBlastTempx2\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void calibrateTemp (unsigned charreference)"

.PP
 Function: calibrationTemp(unsigned char reference)
.PP
Include: \fBTemp\&.h\fP
.PP
Description: calibrates the temperature sensor by updating the calibration offset variable
.PP
Arguments: reference - Reference temperature in deg C
.PP
Returns: None
.PP
Note: This function does not perform a temperature read, but uses the last value\&. This is because the readTemp function automatically calibrate\&. 
.SS "void configureTemp (void)"

.PP
 Function: \fBconfigureTemp(void)\fP
.PP
Include: Temp
.PP
Description: Configures the temperature module for use
.PP
Arguments: None
.PP
Returns: None 
.SS "unsigned char getTemp (void)"

.PP
 Function: calibrationTemp(unsigned char reference)
.PP
Include: \fBTemp\&.h\fP
.PP
Description: calibrates the temperature sensor by updating the calibration offset variable
.PP
Arguments: reference - Reference temperature in deg C
.PP
Returns: None 
.SS "unsigned char rawTemp (void)"

.PP
 Function: \fBrawTemp(void)\fP
.PP
Include: \fBTemp\&.h\fP
.PP
Description: Returns the raw (uncalibrated temperature)
.PP
Arguments: None
.PP
Returns: Temp (in deg celsius) as an unsigned char 
.SS "unsigned char readTemp (void)"

.PP
 Function: \fBreadTemp(void)\fP
.PP
Include: \fBTemp\&.h\fP
.PP
Description: Reads the temperature from the TEMP sensor
.PP
Arguments: None
.PP
Returns: Temp (in deg celsius) as an unsigned char 
.SS "unsigned char readTempx2 (void)"

.PP
 Function: \fBreadTempx2(void)\fP
.PP
Include: \fBTemp\&.h\fP
.PP
Description: Reads the temperature from the Temp sensor
.PP
Arguments: None
.PP
Returns: temp x 2 (in deg celsius) as an unsigned char
.PP
\fBTodo\fP
.RS 4
Test and debug this function 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "signed char calibration_offset = 0\fC [static]\fP"

.PP
 File: \fBTemp\&.c\fP Author: Grant
.PP
Description: Contains all the functionality for the Temp module\&.
.PP
Duties: -Samples the temperature sensor -Stores the last temperature value -Calibrates the temperature sensor
.PP
Functions:
.PP
Created on 7 September 2014, 4:12 PM 
.SS "unsigned char lastTempx2\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
