.TH "Temp.h" 3 "Tue Oct 21 2014" "Version V1.0" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Temp.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBconfigureTemp\fP (void)"
.br
.ti -1c
.RI "unsigned char \fBrawTemp\fP (void)"
.br
.ti -1c
.RI "unsigned char \fBreadTemp\fP (void)"
.br
.ti -1c
.RI "unsigned char \fBreadTempx2\fP (void)"
.br
.ti -1c
.RI "void \fBcalibrateTemp\fP (unsigned char reference)"
.br
.ti -1c
.RI "unsigned char \fBgetTemp\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void calibrateTemp (unsigned charreference)"

.PP
Definition at line 117 of file Temp\&.c\&.
.SS "void configureTemp (void)"

.PP
Definition at line 27 of file Temp\&.c\&.
.SS "unsigned char getTemp (void)"

.PP
Definition at line 134 of file Temp\&.c\&.
.SS "unsigned char rawTemp (void)"

.PP
Definition at line 97 of file Temp\&.c\&.
.SS "unsigned char readTemp (void)"

.PP
Definition at line 75 of file Temp\&.c\&.
.SS "unsigned char readTempx2 (void)"

.PP
Definition at line 43 of file Temp\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
