.TH "todo" 3 "Wed Oct 22 2014" "Version V1.1" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBFile \fBConfigRegs18f4520\&.h\fP \fP" 1c
Consider if Watchdog Timer should be enabled for production code, and add WDT management code if so\&.
.PP
Consider if Stack Overflow Reset should be enabled for production code\&. It may be better not to, as there is no re-entrant or recursive code, or dynamic memory allocation here - if the code loads statically it should run\&.
.PP
Change startup code c016iz\&.c so that everything (including initialised variables) correctly re-starts if \fBmain()\fP ever exits or a BOR or WDT reset occurs\&. 
.PP

