.TH "Tracking.h" 3 "Tue Oct 21 2014" "Version V1.0" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tracking.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTRACK_INT\fP   0"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBconfigureTracking\fP (void)"
.br
.ti -1c
.RI "void \fBsearch\fP (\fBsystemState\fP *state)"
.br
.ti -1c
.RI "\fBTrackingData\fP \fBtrack\fP (\fBsystemState\fP *state)"
.br
.ti -1c
.RI "void \fBtrackingISR\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TRACK_INT   0"

.PP
Definition at line 11 of file Tracking\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void configureTracking (void)"

.PP
Definition at line 32 of file Tracking\&.c\&.
.SS "void search (\fBsystemState\fP *state)"

.PP
Definition at line 50 of file Tracking\&.c\&.
.SS "\fBTrackingData\fP track (\fBsystemState\fP *state)"

.PP
Definition at line 130 of file Tracking\&.c\&.
.SS "void trackingISR (void)"

.PP
Definition at line 111 of file Tracking\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
