.TH "TrackingData" 3 "Tue Oct 21 2014" "Version V1.0" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TrackingData \- 
.PP
Stores the current target information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Common\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBdistance\fP"
.br
.ti -1c
.RI "int \fBazimuth\fP"
.br
.ti -1c
.RI "int \fBinclination\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Stores the current target information\&. 


.PP
 typedef of \fBTrackingData\fP struct
.PP
Description: Stores distance, azimuth and inclination tracking data to the target\&. This struct is used by the tracking function and others to communicate the position of the target 
.PP
Definition at line 87 of file Common\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int azimuth"

.PP
Definition at line 90 of file Common\&.h\&.
.SS "unsigned int distance"

.PP
Definition at line 89 of file Common\&.h\&.
.SS "int inclination"

.PP
Definition at line 91 of file Common\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
