.TH "TrackingData" 3 "Sun Oct 26 2014" "Version V1.1" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TrackingData \- 
.PP
Stores the current target information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Common\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBdistance\fP"
.br
.ti -1c
.RI "int \fBazimuth\fP"
.br
.ti -1c
.RI "int \fBinclination\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Stores the current target information\&. 


.PP
 typedef of \fBTrackingData\fP struct
.PP
Description: Stores distance, azimuth and inclination tracking data to the target\&. This struct is used by the tracking function and others to communicate the position of the target 
.SH "Field Documentation"
.PP 
.SS "int azimuth"

.SS "unsigned int distance"

.SS "int inclination"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
