.TH "TrackingData" 3 "Tue Oct 21 2014" "Version V1.0" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TrackingData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Common\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBdistance\fP"
.br
.ti -1c
.RI "int \fBazimuth\fP"
.br
.ti -1c
.RI "int \fBinclination\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file Common\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int azimuth"

.PP
Definition at line 53 of file Common\&.h\&.
.SS "unsigned int distance"

.PP
Definition at line 52 of file Common\&.h\&.
.SS "int inclination"

.PP
Definition at line 54 of file Common\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
