.TH "Tracking.c" 3 "Tue Oct 21 2014" "Version V1.0" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tracking.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Common\&.h'\fP
.br
\fC#include 'Range\&.h'\fP
.br
\fC#include 'PanTilt\&.h'\fP
.br
\fC#include <delays\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBdiff\fP   5"
.br
.ti -1c
.RI "#define \fBTARGET_RAD\fP   30"
.br
.ti -1c
.RI "#define \fBTIMER\fP   \fBTMR2\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBconfigureTracking\fP (void)"
.br
.ti -1c
.RI "void \fBsearch\fP (\fBsystemState\fP *state)"
.br
.ti -1c
.RI "void \fBtrackingISR\fP (void)"
.br
.ti -1c
.RI "\fBTrackingData\fP \fBtrack\fP (\fBsystemState\fP *state)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define diff   5"

.PP
Definition at line 14 of file Tracking\&.c\&.
.SS "#define TARGET_RAD   30"

.PP
Definition at line 15 of file Tracking\&.c\&.
.SS "#define TIMER   \fBTMR2\fP"

.SH "Function Documentation"
.PP 
.SS "void configureTracking (void)"

.PP
Definition at line 32 of file Tracking\&.c\&.
.SS "void search (\fBsystemState\fP *state)"

.PP
Definition at line 50 of file Tracking\&.c\&.
.SS "\fBTrackingData\fP track (\fBsystemState\fP *state)"

.PP
Definition at line 130 of file Tracking\&.c\&.
.SS "void trackingISR (void)"

.PP
Definition at line 111 of file Tracking\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
