.TH "Yavin4DefenceSystem/Code/Tracking.c" 3 "Sun Oct 26 2014" "Version V1.1" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Yavin4DefenceSystem/Code/Tracking.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Common\&.h'\fP
.br
\fC#include 'Range\&.h'\fP
.br
\fC#include 'PanTilt\&.h'\fP
.br
\fC#include <delays\&.h>\fP
.br
\fC#include <timers\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBTargetStateData\fP"
.br
.RI "\fIStores data about the last target track\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBdiff\fP   8"
.br
.ti -1c
.RI "#define \fBTARGET_RAD\fP   30"
.br
.ti -1c
.RI "#define \fBsampleTargetState\fP   weight"
.br
.ti -1c
.RI "#define \fBTIMER\fP   \fBTMR2\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static char \fBnewAngle\fP (\fBTargetStateData\fP target_data)"
.br
.ti -1c
.RI "void \fBconfigureTracking\fP (void)"
.br
.ti -1c
.RI "void \fBsearch\fP (\fBsystemState\fP *state)"
.br
.ti -1c
.RI "void \fBtrackingISR\fP (void)"
.br
.ti -1c
.RI "\fBTrackingData\fP \fBtrack\fP (\fBsystemState\fP *state)"
.br
.ti -1c
.RI "static \fBDirection\fP \fBprediction\fP (\fBDirection\fP current)"
.br
.ti -1c
.RI "static char \fBnewAngle\fP (char angle, \fBTargetStateData\fP target_data)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define diff   8"

.PP
 File: \fBTracking\&.c\fP Author: Grant
.PP
Description: Contains all the functionality for the Tracking Module\&. This module contains the functionality and algorithms used to search for, and track the target\&. This module makes use of PanTilt, Range and Temp modules, and configures them automatically from a call to configureTrack()\&.
.PP
Duties: -Control and coordinate Pan Tilt and range sensors -Implement searching and tracking algorithms -Predict next position of target???
.PP
Functions:
.PP
Created on 15 September 2014, 1:42 PM 
.SS "#define sampleTargetState   weight"

.SS "#define TARGET_RAD   30"

.SS "#define TIMER   \fBTMR2\fP"

.SH "Function Documentation"
.PP 
.SS "void configureTracking (void)"

.SS "static char newAngle (\fBTargetStateData\fPtarget_data)\fC [static]\fP"

.SS "static char newAngle (charangle, \fBTargetStateData\fPtarget_data)\fC [static]\fP"

.SS "static \fBDirection\fP prediction (\fBDirection\fPcurrent)\fC [static]\fP"

.SS "void search (\fBsystemState\fP *state)"

.SS "\fBTrackingData\fP track (\fBsystemState\fP *state)"

.SS "void trackingISR (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
