.TH "User_Interface.h" 3 "Tue Oct 21 2014" "Version V1.0" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
User_Interface.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSER_INT\fP   0"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdisplay\fP (\fBTrackingData\fP data)"
.br
.ti -1c
.RI "void \fBuserISR\fP (void)"
.br
.ti -1c
.RI "void \fBconfigUSER\fP (void)"
.br
.ti -1c
.RI "char \fBuserEmpty\fP (void)"
.br
.ti -1c
.RI "char \fBuserPop\fP (void)"
.br
.ti -1c
.RI "char \fBuserPeek\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define USER_INT   0"

.PP
Definition at line 12 of file User_Interface\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void configUSER (void)"

.PP
 Function: \fBconfigUSER(void)\fP
.PP
Include: \fBUser_Interface\&.h\fP
.PP
Description: Configures the user interface for use
.PP
Arguments: None
.PP
Returns: None 
.PP
Definition at line 61 of file User_Interface\&.c\&.
.SS "void display (\fBTrackingData\fPdata)"

.PP
 Function: \fBdisplay(TrackingData data)\fP
.PP
Include: \fBUser_Interface\&.h\fP
.PP
Description: displays the current tracking information
.PP
Arguments: data - Struct which contains all known data concerning the The position of the target\&. A Range of 0 indicates that no target was observed\&.
.PP
Returns: None 
.PP
Definition at line 29 of file User_Interface\&.c\&.
.SS "char userEmpty (void)"

.PP
 Function: \fBuserEmpty(void)\fP
.PP
Include: \fBUser_Interface\&.h\fP
.PP
Description: returns non-zero if the user interface buffer is empty (i\&.e\&. no user input has been detected)
.PP
Arguments: None
.PP
Returns: if the user input buffer is empty 
.PP
Definition at line 109 of file User_Interface\&.c\&.
.SS "void userISR (void)"

.PP
 Function: \fBuserISR(void)\fP
.PP
Include: \fBUser_Interface\&.h\fP
.PP
Description: Acts as the ISR for the User_interface module
.PP
Arguments: None
.PP
Returns: None 
.PP
Definition at line 45 of file User_Interface\&.c\&.
.SS "char userPeek (void)"

.PP
 Function: \fBuserPeek(void)\fP
.PP
Include: \fBUser_Interface\&.h\fP
.PP
Description: returns a character in the user_Interface buffer without removing it from the buffer
.PP
Arguments: None
.PP
Returns: a character in the user interface buffer 
.PP
Definition at line 144 of file User_Interface\&.c\&.
.SS "char userPop (void)"

.PP
 Function: \fBuserPop(void)\fP
.PP
Include: \fBUser_Interface\&.h\fP
.PP
Description: pops a character from the user interface receive buffer
.PP
Arguments: None
.PP
Returns: a character poped from the user Interface buffer 
.PP
Definition at line 125 of file User_Interface\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
