.TH "Yavin4DefenceSystem/Code/User_Interface.h" 3 "Sun Oct 26 2014" "Version V1.1" "Yavin IV Death Star Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Yavin4DefenceSystem/Code/User_Interface.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Common\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSER_INT\fP   (\fBRB_INT\fP || \fBINT0_INT\fP || \fBINT1_INT\fP )"
.br
.ti -1c
.RI "#define \fBCONFIRM_CHAR\fP   0x0D"
.br
.ti -1c
.RI "#define \fBBACK_CHAR\fP   0x1B"
.br
.ti -1c
.RI "#define \fBUSER_H\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdisplay\fP (\fBTrackingData\fP data)"
.br
.ti -1c
.RI "void \fBuserISR\fP (void)"
.br
.ti -1c
.RI "void \fBconfigUSER\fP (void)"
.br
.ti -1c
.RI "char \fBuserEmpty\fP (void)"
.br
.ti -1c
.RI "char \fBuserPop\fP (void)"
.br
.ti -1c
.RI "char \fBuserPeek\fP (void)"
.br
.ti -1c
.RI "unsigned int \fBreadDial\fP (unsigned int max)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BACK_CHAR   0x1B"

.SS "#define CONFIRM_CHAR   0x0D"

.SS "#define USER_H"

.SS "#define USER_INT   (\fBRB_INT\fP || \fBINT0_INT\fP || \fBINT1_INT\fP )"

.SH "Function Documentation"
.PP 
.SS "void configUSER (void)"

.PP
 Function: \fBconfigUSER(void)\fP
.PP
Include: \fBUser_Interface\&.h\fP
.PP
Description: Configures the user interface for use
.PP
Arguments: None
.PP
Returns: None 
.SS "void display (\fBTrackingData\fPdata)"

.PP
 Function: \fBdisplay(TrackingData data)\fP
.PP
Include: \fBUser_Interface\&.h\fP
.PP
Description: displays the current tracking information
.PP
Arguments: data - Struct which contains all known data concerning the The position of the target\&. A Range of 0 indicates that no target was observed\&.
.PP
Returns: None 
.SS "unsigned int readDial (unsigned intmax)"

.PP
 Function: readDial(void)
.PP
Include:
.PP
Description: Read the position of the dial
.PP
Arguments: None
.PP
Returns: The dial position scaled by 
.SS "char userEmpty (void)"

.PP
 Function: \fBuserEmpty(void)\fP
.PP
Include: \fBUser_Interface\&.h\fP
.PP
Description: returns non-zero if the user interface buffer is empty (i\&.e\&. no user input has been detected)
.PP
Arguments: None
.PP
Returns: if the user input buffer is empty 
.SS "void userISR (void)"

.PP
 Function: \fBuserISR(void)\fP
.PP
Include: \fBUser_Interface\&.h\fP
.PP
Description: Acts as the ISR for the User_interface module
.PP
Arguments: None
.PP
Returns: None 
.SS "char userPeek (void)"

.PP
 Function: \fBuserPeek(void)\fP
.PP
Include: \fBUser_Interface\&.h\fP
.PP
Description: returns a character in the user_Interface buffer without removing it from the buffer
.PP
Arguments: None
.PP
Returns: a character in the user interface buffer 
.SS "char userPop (void)"

.PP
 Function: \fBuserPop(void)\fP
.PP
Include: \fBUser_Interface\&.h\fP
.PP
Description: pops a character from the user interface receive buffer
.PP
Arguments: None
.PP
Returns: a character poped from the user Interface buffer 
.SH "Author"
.PP 
Generated automatically by Doxygen for Yavin IV Death Star Tracker from the source code\&.
